changelog:
  exclude:
    labels:
      - semver-ignore
  categories:
    - title: Breaking Changes
      labels:
        - semver-major
    - title: New Features
      labels:
        - semver-minor
    - title: Patches
      labels:
        - semver-patch
    - title: Other Changes
      labels:
        - semver-docs
        - "*"
