input_topic = 'somemachine_rawEvents'
output_topic = 'somemachine_events'

frame_queue_poll_interval_ms = 100
max_events_per_message = 100000
reference_time_tolerance_ns = 100
expiry_offset_ms = 500

[kafka_producer]
"bootstrap.servers" = "livedata.isis.cclrc.ac.uk:31092"
"enable.idempotence" = "true"

[kafka_consumer]
"bootstrap.servers" = "livedata.isis.cclrc.ac.uk:31092"
"group.id" = "kafka-event-aggregator-somemachine"
"enable.auto.commit" = "true"
"auto.commit.interval.ms" = "5000"
