name: Build
on: [push, workflow_call]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - uses: Nugine/setup-flatc@e7855e994773ce90094a3f1626d4afc9080c23ae
        with:
          version: "25.12.19"
      - name: install stable rust
        run: rustup install stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - name: Unit tests
        run: cargo test
      - name: Unit tests (release mode)
        run: cargo test --release
      - name: Build (debug)
        run: cargo build
      - name: Build (release)
        run: cargo build --release
      - name: Format check
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy -- --deny warnings
      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('debug-{0}', matrix.os) }}
          path: |
            target/debug/kafka_event_aggregator
            target/debug/kafka_event_aggregator.exe
            target/debug/kafka_event_aggregator.pdb
          if-no-files-found: error
          retention-days: 1
      - name: Upload artifacts (release)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('release-{0}', matrix.os) }}
          path: |
            target/release/kafka_event_aggregator
            target/release/kafka_event_aggregator.exe
            target/release/kafka_event_aggregator.pdb
          if-no-files-found: error
          retention-days: 1
  docs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: install stable rust
        run: rustup install stable
      - uses: Swatinem/rust-cache@v2
      - name: Build docs
        run: cargo doc --no-deps
      - name: Generate index.html
        # u wot?
        run: |
          echo '<meta http-equiv="refresh" content="0; url=kafka_event_aggregator/">' > target/doc/index.html
      - name: Upload artifacts (docs)
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: |
            target/doc
          if-no-files-found: error
          retention-days: 1
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
          force_orphan: true
  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [tests, docs]
    steps:
    - run: exit 1
      # see https://stackoverflow.com/a/67532120/4907315
      if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
